import type { TrainingExample } from "./types.js";

export const trainingData: TrainingExample[] = [
	// Technical
	{ text: "I can't log in to my account", label: "technical" },
	{ text: "Getting error message when trying to submit", label: "technical" },
	{ text: "Website keeps crashing and won't load", label: "technical" },
	{ text: "How do I reset my password", label: "technical" },
	{ text: "The application is broken and not responding", label: "technical" },
	{ text: "Cannot upload files to the system", label: "technical" },
	{ text: "Browser compatibility issues with the page", label: "technical" },
	{ text: "Server error 500 on checkout", label: "technical" },
	{ text: "My account was hacked need to secure it", label: "technical" },
	{ text: "Authentication failed two factor not working", label: "technical" },
	{ text: "App keeps freezing when I use it", label: "technical" },
	{ text: "How to troubleshoot connection problems", label: "technical" },
	{ text: "Performance issue the page loads slow", label: "technical" },
	{ text: "Notifications not appearing in the app", label: "technical" },
	{ text: "Can't download the latest update", label: "technical" },
	{ text: "Email verification link not working", label: "technical" },
	{ text: "Unexpected logout from my account", label: "technical" },
	{ text: "Video playback fails on mobile devices", label: "technical" },
	{ text: "App crashes when opening settings", label: "technical" },
	{ text: "How to clear cache to fix errors", label: "technical" },
	{ text: "Data not syncing between devices", label: "technical" },
	{ text: "Unable to connect to the server", label: "technical" },
	{ text: "Error code 403 when accessing dashboard", label: "technical" },
	{ text: "Cannot reset password via email link", label: "technical" },
	{
		text: "Problems with browser extensions causing errors",
		label: "technical",
	},
	{ text: "Login page spins forever on submit", label: "technical" },
	{ text: "Captcha fails and blocks sign in", label: "technical" },
	{ text: "File export stuck at 0 percent", label: "technical" },
	{ text: "Push notifications stopped after update", label: "technical" },
	{ text: "Error 502 when opening reports", label: "technical" },
	{ text: "Images not loading in the dashboard", label: "technical" },
	{ text: "Unable to install the desktop app", label: "technical" },
	{ text: "Two factor code never arrives", label: "technical" },
	{ text: "App signs me out every few minutes", label: "technical" },
	{ text: "Search feature returns blank results", label: "technical" },
	{ text: "Login form throws a script error", label: "technical" },
	{ text: "Password reset email never arrives", label: "technical" },
	{ text: "Mobile app stuck on loading screen", label: "technical" },
	{ text: "Audio does not play in the tutorial", label: "technical" },
	{ text: "Cannot connect after changing networks", label: "technical" },
	{ text: "System times out when saving changes", label: "technical" },
	{ text: "Export to PDF fails with an error", label: "technical" },
	{ text: "The widget does not render on Safari", label: "technical" },
	{ text: "Cannot verify my phone number", label: "technical" },
	{ text: "Link in the app opens a blank page", label: "technical" },
	{ text: "Settings page shows a blank screen", label: "technical" },
	{ text: "Upload completes but file is missing", label: "technical" },
	{ text: "The download button does nothing", label: "technical" },
	{ text: "Getting 401 unauthorized on login", label: "technical" },
	{ text: "My session expires too quickly", label: "technical" },
	{ text: "I see a CORS error in the console", label: "technical" },
	{ text: "Billing page loads with a spinner only", label: "technical" },
	{ text: "Cannot update profile picture", label: "technical" },
	{ text: "Two factor backup codes not accepted", label: "technical" },
	{ text: "Notifications are delayed by hours", label: "technical" },
	{ text: "The app is slow on Android devices", label: "technical" },
	{ text: "Search results show unrelated items", label: "technical" },
	{ text: "Import from CSV fails at row 10", label: "technical" },
	{ text: "Getting blank emails from the system", label: "technical" },
	{ text: "Cannot delete an old device session", label: "technical" },
	{ text: "Error 504 gateway timeout on reports", label: "technical" },
	{ text: "App crashes when scanning a QR code", label: "technical" },
	{ text: "The map view does not load", label: "technical" },
	{ text: "Integration webhook not firing", label: "technical" },
	{ text: "Push tokens are not registering", label: "technical" },
	{ text: "Upload speed is extremely slow", label: "technical" },
	{ text: "The login button is disabled", label: "technical" },
	{ text: "I cannot enable dark mode", label: "technical" },
	{ text: "Data export generates an empty file", label: "technical" },
	{ text: "The desktop app fails to auto update", label: "technical" },
	{ text: "VPN users cannot access the site", label: "technical" },
	{ text: "Video upload stuck in processing", label: "technical" },
	{ text: "App hangs when opening notifications", label: "technical" },
	{ text: "Getting duplicate emails from alerts", label: "technical" },
	{ text: "The calendar view is not loading", label: "technical" },
	{ text: "Cannot change my email address", label: "technical" },
	{ text: "System says token is invalid", label: "technical" },
	{ text: "Captcha keeps looping on submit", label: "technical" },
	{ text: "I cannot join a video call", label: "technical" },
	{ text: "Attachment previews are broken", label: "technical" },
	{ text: "The app uses too much battery", label: "technical" },
	{ text: "Location permission is ignored", label: "technical" },
	{ text: "Webhook signature validation fails", label: "technical" },
	{ text: "Reports page shows undefined values", label: "technical" },
	{ text: "The API returns a 429 rate limit", label: "technical" },

	// Financial
	{ text: "My payment didn't go through", label: "financial" },
	{ text: "I need an invoice for my purchase", label: "financial" },
	{ text: "What is the billing amount for my order", label: "financial" },
	{ text: "How do I request a refund", label: "financial" },
	{ text: "I was charged twice for the same transaction", label: "financial" },
	{ text: "Where can I see my transaction history", label: "financial" },
	{ text: "What payment methods do you accept", label: "financial" },
	{ text: "How much does the premium plan cost", label: "financial" },
	{ text: "Can I get a discount on my subscription", label: "financial" },
	{ text: "Tax calculation for my order is wrong", label: "financial" },
	{ text: "Subscription cancellation process", label: "financial" },
	{ text: "Currency conversion rate question", label: "financial" },
	{ text: "Payment plan options available", label: "financial" },
	{ text: "How to update billing address", label: "financial" },
	{ text: "Receipt not received after payment", label: "financial" },
	{ text: "Refund not processed yet", label: "financial" },
	{ text: "How to apply promo code to my order", label: "financial" },
	{ text: "Bank account details not updated", label: "financial" },
	{ text: "How to set up auto payment", label: "financial" },
	{ text: "Payment failed due to card limit", label: "financial" },
	{ text: "Order amount charged incorrectly", label: "financial" },
	{ text: "Need confirmation of my subscription payment", label: "financial" },
	{ text: "Change payment method for future bills", label: "financial" },
	{ text: "Refund policy for canceled orders", label: "financial" },
	{ text: "Why was I billed after canceling", label: "financial" },
	{ text: "Need a copy of last month's invoice", label: "financial" },
	{ text: "Chargeback dispute for my payment", label: "financial" },
	{ text: "My card keeps getting declined", label: "financial" },
	{ text: "Upgrade cost for annual plan", label: "financial" },
	{ text: "Can you resend the receipt", label: "financial" },
	{ text: "VAT number for my company account", label: "financial" },
	{ text: "Prorated refund for plan downgrade", label: "financial" },
	{ text: "How to change billing cycle date", label: "financial" },
	{ text: "Invoice needs company address update", label: "financial" },
	{ text: "Can you split this payment", label: "financial" },
	{ text: "Need a proforma invoice", label: "financial" },
	{ text: "Refund was short by a few dollars", label: "financial" },
	{ text: "Why is there a pending charge", label: "financial" },
	{ text: "Card verification fee was unexpected", label: "financial" },
	{ text: "How do I add a purchase order number", label: "financial" },
	{ text: "Can I pay by bank transfer", label: "financial" },
	{ text: "Upgrade charged immediately", label: "financial" },
	{ text: "Discount not applied at checkout", label: "financial" },
	{ text: "Need a refund to the original card", label: "financial" },
	{ text: "Payment shows as reversed", label: "financial" },
	{ text: "Charge for add ons is incorrect", label: "financial" },
	{ text: "Please send a receipt in PDF", label: "financial" },
	{ text: "My invoice lists the wrong tax rate", label: "financial" },
	{ text: "Billing email needs to be changed", label: "financial" },
	{ text: "When will my refund appear", label: "financial" },
	{ text: "Subscription renewal price increased", label: "financial" },
	{ text: "I need a quote for 50 licenses", label: "financial" },
	{ text: "Can you extend my trial billing", label: "financial" },
	{ text: "Why did you charge my old card", label: "financial" },
	{ text: "Credit note for returned order", label: "financial" },
	{ text: "Payment receipt missing my VAT", label: "financial" },
	{ text: "The invoice currency is wrong", label: "financial" },
	{ text: "I need a statement of account", label: "financial" },
	{ text: "Auto renewal should be off", label: "financial" },
	{ text: "Invoice should be under our company", label: "financial" },
	{ text: "Bank transfer is pending", label: "financial" },
	{ text: "Billing portal shows zero balance", label: "financial" },
	{ text: "I was charged for a free trial", label: "financial" },
	{ text: "Please refund the duplicate charge", label: "financial" },
	{ text: "Credit card expired update needed", label: "financial" },
	{ text: "How to download all invoices", label: "financial" },
	{ text: "Invoice date needs correction", label: "financial" },
	{ text: "We need a W9 for billing", label: "financial" },
	{ text: "Refunded to wrong payment method", label: "financial" },
	{ text: "Charge appears as a different name", label: "financial" },
	{ text: "I need net 30 terms", label: "financial" },
	{ text: "What is the late fee policy", label: "financial" },
	{ text: "Charge for shipping seems too high", label: "financial" },
	{ text: "Payment failed with 3D secure", label: "financial" },
	{ text: "Can I pay quarterly instead", label: "financial" },
	{ text: "Please remove tax for exemption", label: "financial" },
	{ text: "Refund for unused days", label: "financial" },
	{ text: "Need invoice for reimbursement", label: "financial" },
	{ text: "Billing address cannot be updated", label: "financial" },
	{ text: "Change card for auto renew", label: "financial" },
	{ text: "Dispute fee was added", label: "financial" },
	{ text: "Overcharged for extra seats", label: "financial" },
	{ text: "How do I add another payer", label: "financial" },
	{ text: "Refund expected for canceled trial", label: "financial" },

	// Informational
	{text: "What are your working hours?", label: "informational"},
	{ text: "What are your working hours", label: "informational" },
	{ text: "How to contact customer support", label: "informational" },
	{ text: "What features does your service offer", label: "informational" },
	{ text: "Where is your office located", label: "informational" },
	{ text: "Do you have a mobile app", label: "informational" },
	{ text: "What is your privacy policy", label: "informational" },
	{ text: "How long does shipping take", label: "informational" },
	{ text: "Can you provide documentation", label: "informational" },
	{ text: "What are your return policies", label: "informational" },
	{ text: "Do you offer API access", label: "informational" },
	{ text: "What companies use your services", label: "informational" },
	{ text: "Available languages support", label: "informational" },
	{ text: "Team size and company experience", label: "informational" },
	{ text: "Awards and certifications received", label: "informational" },
	{ text: "Do you provide onboarding support", label: "informational" },
	{ text: "Do you have a FAQ section", label: "informational" },
	{ text: "Where can I find tutorials", label: "informational" },
	{ text: "How to subscribe to the newsletter", label: "informational" },
	{ text: "Is there a community forum", label: "informational" },
	{ text: "Where can I read user reviews", label: "informational" },
	{ text: "How to request technical documentation", label: "informational" },
	{ text: "Are there training materials available", label: "informational" },
	{ text: "What is your company mission", label: "informational" },
	{ text: "Do you have affiliate programs", label: "informational" },
	{ text: "What regions do you support", label: "informational" },
	{ text: "Is there a status page for outages", label: "informational" },
	{ text: "How do I create a new account", label: "informational" },
	{ text: "What are your service level terms", label: "informational" },
	{ text: "Do you offer in person training", label: "informational" },
	{ text: "Where can I see product updates", label: "informational" },
	{ text: "Do you provide a sandbox environment", label: "informational" },
	{ text: "What is your uptime guarantee", label: "informational" },
	{ text: "Is the service available on weekends", label: "informational" },
	{ text: "How can I become a partner", label: "informational" },
	{ text: "What is included in the basic plan", label: "informational" },
	{ text: "Do you support single sign on", label: "informational" },
	{ text: "Where is the help center located", label: "informational" },
	{ text: "How do I update my profile info", label: "informational" },
	{ text: "Do you have case studies", label: "informational" },
	{ text: "What browsers are supported", label: "informational" },
	{ text: "Is there a product roadmap", label: "informational" },
	{ text: "Where can I see pricing details", label: "informational" },
	{ text: "Do you offer nonprofit discounts", label: "informational" },
	{ text: "How can I join the beta program", label: "informational" },
	{ text: "Is phone support available", label: "informational" },
	{ text: "What is your response time", label: "informational" },
	{ text: "Do you have integration guides", label: "informational" },
	{ text: "Where can I check system status", label: "informational" },
	{ text: "Do you support data export", label: "informational" },
	{ text: "What is the minimum contract term", label: "informational" },
	{ text: "Are there onboarding videos", label: "informational" },
	{ text: "Do you offer white labeling", label: "informational" },
	{ text: "How do I change my password", label: "informational" },
	{ text: "Is there a free trial", label: "informational" },
	{ text: "Where can I see release notes", label: "informational" },
	{ text: "What is your data retention policy", label: "informational" },
	{ text: "Do you have a compliance page", label: "informational" },
	{ text: "Can I request a demo", label: "informational" },
	{ text: "What is your refund policy", label: "informational" },
	{ text: "Do you support custom domains", label: "informational" },
	{ text: "Where can I manage my subscriptions", label: "informational" },
	{ text: "How do I delete my account", label: "informational" },
	{ text: "Is there an onboarding checklist", label: "informational" },
	{ text: "What payment providers do you use", label: "informational" },
	{ text: "Do you have developer docs", label: "informational" },
	{ text: "What is the support email", label: "informational" },
	{ text: "Do you support multi factor auth", label: "informational" },
	{ text: "What is your company history", label: "informational" },
	{ text: "How do I submit feedback", label: "informational" },
	{ text: "Do you provide data migration", label: "informational" },
	{ text: "What is the security contact", label: "informational" },
	{ text: "Where can I see terms of service", label: "informational" },
	{ text: "Do you offer priority support", label: "informational" },
	{ text: "Is there a user guide", label: "informational" },
	{ text: "Do you have a knowledge base", label: "informational" },
	{ text: "What is the refund timeline", label: "informational" },
	{ text: "Is there a self service portal", label: "informational" },
	{ text: "Where can I find webinars", label: "informational" },
	{ text: "Do you support phone number login", label: "informational" },
	{ text: "What is your accessibility policy", label: "informational" },
	{ text: "Is there a student discount", label: "informational" },
	{ text: "How do I update notification prefs", label: "informational" },
	{ text: "Where can I see account activity", label: "informational" },
	{ text: "Do you have partner resources", label: "informational" },
	{ text: "How do I request a feature", label: "informational" },
];
