export type RequestLabel = "technical" | "financial" | "informational";

export interface TrainingExample {
	text: string;
	label: RequestLabel;
}

export const trainingData: TrainingExample[] = [
	// Technical
	{ text: "I can't log in to my account", label: "technical" },
	{ text: "Getting error message when trying to submit", label: "technical" },
	{ text: "Website keeps crashing and won't load", label: "technical" },
	{ text: "How do I reset my password", label: "technical" },
	{ text: "The application is broken and not responding", label: "technical" },
	{ text: "Cannot upload files to the system", label: "technical" },
	{ text: "Browser compatibility issues with the page", label: "technical" },
	{ text: "Server error 500 on checkout", label: "technical" },
	{ text: "My account was hacked need to secure it", label: "technical" },
	{ text: "Authentication failed two factor not working", label: "technical" },
	{ text: "App keeps freezing when I use it", label: "technical" },
	{ text: "How to troubleshoot connection problems", label: "technical" },
	{ text: "Performance issue the page loads slow", label: "technical" },
	{ text: "Notifications not appearing in the app", label: "technical" },
	{ text: "Can't download the latest update", label: "technical" },
	{ text: "Email verification link not working", label: "technical" },
	{ text: "Unexpected logout from my account", label: "technical" },
	{ text: "Video playback fails on mobile devices", label: "technical" },
	{ text: "App crashes when opening settings", label: "technical" },
	{ text: "How to clear cache to fix errors", label: "technical" },
	{ text: "Data not syncing between devices", label: "technical" },
	{ text: "Unable to connect to the server", label: "technical" },
	{ text: "Error code 403 when accessing dashboard", label: "technical" },
	{ text: "Cannot reset password via email link", label: "technical" },
	{
		text: "Problems with browser extensions causing errors",
		label: "technical",
	},

	// Financial
	{ text: "My payment didn't go through", label: "financial" },
	{ text: "I need an invoice for my purchase", label: "financial" },
	{ text: "What is the billing amount for my order", label: "financial" },
	{ text: "How do I request a refund", label: "financial" },
	{ text: "I was charged twice for the same transaction", label: "financial" },
	{ text: "Where can I see my transaction history", label: "financial" },
	{ text: "What payment methods do you accept", label: "financial" },
	{ text: "How much does the premium plan cost", label: "financial" },
	{ text: "Can I get a discount on my subscription", label: "financial" },
	{ text: "Tax calculation for my order is wrong", label: "financial" },
	{ text: "Subscription cancellation process", label: "financial" },
	{ text: "Currency conversion rate question", label: "financial" },
	{ text: "Payment plan options available", label: "financial" },
	{ text: "How to update billing address", label: "financial" },
	{ text: "Receipt not received after payment", label: "financial" },
	{ text: "Refund not processed yet", label: "financial" },
	{ text: "How to apply promo code to my order", label: "financial" },
	{ text: "Bank account details not updated", label: "financial" },
	{ text: "How to set up auto payment", label: "financial" },
	{ text: "Payment failed due to card limit", label: "financial" },
	{ text: "Order amount charged incorrectly", label: "financial" },
	{ text: "Need confirmation of my subscription payment", label: "financial" },
	{ text: "Change payment method for future bills", label: "financial" },
	{ text: "Refund policy for canceled orders", label: "financial" },

	// Informational
	{ text: "What are your working hours", label: "informational" },
	{ text: "How to contact customer support", label: "informational" },
	{ text: "What features does your service offer", label: "informational" },
	{ text: "Where is your office located", label: "informational" },
	{ text: "Do you have a mobile app", label: "informational" },
	{ text: "What is your privacy policy", label: "informational" },
	{ text: "How long does shipping take", label: "informational" },
	{ text: "Can you provide documentation", label: "informational" },
	{ text: "What are your return policies", label: "informational" },
	{ text: "Do you offer API access", label: "informational" },
	{ text: "What companies use your services", label: "informational" },
	{ text: "Available languages support", label: "informational" },
	{ text: "Team size and company experience", label: "informational" },
	{ text: "Awards and certifications received", label: "informational" },
	{ text: "Do you provide onboarding support", label: "informational" },
	{ text: "Do you have a FAQ section", label: "informational" },
	{ text: "Where can I find tutorials", label: "informational" },
	{ text: "How to subscribe to the newsletter", label: "informational" },
	{ text: "Is there a community forum", label: "informational" },
	{ text: "Where can I read user reviews", label: "informational" },
	{ text: "How to request technical documentation", label: "informational" },
	{ text: "Are there training materials available", label: "informational" },
	{ text: "What is your company mission", label: "informational" },
	{ text: "Do you have affiliate programs", label: "informational" },
];
